#!/bin/sh
#shellcheck source=../environment.in
. ./environment

"${scripts}/bareos-config" initialize_database_driver
. "${rscripts}/functions"

print_debug "drop database \"${db_name}\" (${DBTYPE})"
"${scripts}/drop_bareos_database" "${DBTYPE}" >/dev/null 2>&1

print_debug "creating database \"${db_name}\" (${DBTYPE})"
"${scripts}/create_bareos_database" "${DBTYPE}" >/dev/null 2>&1
"${scripts}/make_bareos_tables" "${DBTYPE}" >/dev/null 2>&1
"${scripts}/grant_bareos_privileges" "${DBTYPE}" >/dev/null 2>&1

if lsof="$(command -v lsof)"; then
  for port in $BASEPORT $BAREOS_DIRECTOR_PORT $BAREOS_STORAGE_PORT \
    $BAREOS_STORAGE2_PORT $BAREOS_FD_PORT $MINIO_PORT; do
    if pid=$("${lsof}" -ti "tcp:$port"); then
      print_debug "Killing process listening on $port with PID $pid"
      kill -9 "$pid"
    fi
  done
elif sockstat="$(command -v sockstat)"; then
  for port in $BASEPORT $BAREOS_DIRECTOR_PORT $BAREOS_STORAGE_PORT \
    $BAREOS_STORAGE2_PORT $BAREOS_FD_PORT $MINIO_PORT; do
    pids="$("${sockstat}" -q -l -P tcp -p "$port" | awk '{ print $3 }')"
    if [ "$pids" ]; then
      print_debug "Killing process listening on $port with PID $pids"
      # $pids could contain multiple pids, so we shouldn't quote
      # shellcheck disable=SC2086
      kill -9 $pids
    fi
  done
fi
exit 0
